### ISSUE TITLE
How to define separator characters?

### ISSUE THREAD

**Issue by wolfheart** [antonycourtney/tad#104] opened 2017-06-14 08:31 UTC
How can I define, which separator characters are used in the CSV to be displayed?
- comma, semicolon or tab for cell separators?
- quoting characters for cells?

**Comment by antonycourtney** [comment] 2017-06-16 01:42
Duplicate of #52.  Implementation work and has been completed; An updated version will be published sometime soon. Please subscribe to tad-users mailing list for release announcement.

**Closed** 2017-06-16 01:42 UTC
