### ISSUE TITLE
macOS 11.6.5: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by thanegill** [antonycourtney/tad#169] opened 2022-05-07 01:12 UTC
While opening tad. On an M1.

```
Uncaught Exception:
Error: dlopen(/Applications/Tad.app/Contents/Resources/app.asar.unpacked/node_modules/ac-node-duckdb/build/Release/node-duckdb-addon.node, 1): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
Referenced from: /Applications/Tad.app/Contents/Resources/app.asar.unpacked/node_modules/ac-node-duckdb/build/Release/./libduckdb.dylib (which was built for Mac OS X 12.0)
Expected in: /usr/lib/libc++.1.dylib

at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module._load (node:internal/modules/cjs/loader:829:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
at Module.require (node:internal/modules/cjs/loader:1012:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/Applications/Tad.app/Contents/Resources/app.asar/node_modules/ac-node-duckdb/src/addon-bindings/connection-binding.ts:12:24)
at Module._compile (node:internal/modules/cjs/loader:1116:14)
```

**Comment by mollyow** [comment] 2022-05-16 00:45
I get the same error—also on an M1 mac.

**Comment by bmschmidt** [comment] 2022-05-16 13:11
Same issue. OS X 11.6.1, M1 chip.

```
Uncaught Exception:
Error: dlopen(/Applications/Tad.app/Contents/Resources/app.asar.unpacked/node_modules/ac-node-duckdb/build/Release/node-duckdb-addon.node, 1): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
Referenced from: /Applications/Tad.app/Contents/Resources/app.asar.unpacked/node_modules/ac-node-duckdb/build/Release/./libduckdb.dylib (which was built for Mac OS X 12.0)
Expected in: /usr/lib/libc++.1.dylib

at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module._load (node:internal/modules/cjs/loader:829:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
at Module.require (node:internal/modules/cjs/loader:1012:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/Applications/Tad.app/Contents/Resources/app.asar/node_modules/ac-node-duckdb/src/addon-bindings/connection-binding.ts:12:24)
at Module._compile (node:internal/modules/cjs/loader:1116:14)
```

**Comment by bmschmidt** [comment] 2022-05-16 13:15
Ah duplicate of https://github.com/antonycourtney/tad/issues/167

Solution is to upgrade to OS X 12 or build from source.

**Comment by antonycourtney** [comment] 2022-06-03 20:44
Closing as a duplicate of #167. But great news! I've managed to do a build of Tad that works on macOS 11 and macOS 12. Head on over to the [github Releases](https://github.com/antonycourtney/tad/releases/tag/v0.10.0) and download [Tad-0.10.0.dmg](https://github.com/antonycourtney/tad/releases/download/v0.10.0/tad-0.10.0.dmg) for a DMG that should work on Big Sur or Monterey!

**Closed by antonycourtney** 2022-06-03 20:44 UTC
