### ISSUE TITLE
TypeError: _sqlite2.default.driver.import is not a function

### ISSUE THREAD

**Issue by robbyki** [antonycourtney/tad#121] opened 2018-03-22 21:51 UTC
Getting a Tad Fails to Initialize error pointing to something related to `sqlite2`. Any recommended solutions to this?

**Comment by antonycourtney** [comment] 2018-03-31 21:55
I think this is a duplicate of #120 for which I just pushed a fix. Please see comment in that issue; closing here.

**Closed by antonycourtney** 2018-03-31 21:55 UTC
