### ISSUE TITLE
Support for non standard separated values

### ISSUE THREAD

**Issue by ralphsaunders** [antonycourtney/tad#75] opened 2017-05-31 11:35 UTC
Hi there,

Not sure if this would be a quick win or not, but would be a very useful feature for those of us who're unlucky enough to have to work with non standard CSV data, like "BLM" files. BLM syntax separates fields with a caret `^` rather than a comma `,`. Here's some example data.

    #HEADER#
    Version : 3
    EOF : '^'
    EOR : '~'

    #DEFINITION#
    AGENT_REF^ADDRESS_1^ADDRESS_2^ADDRESS_3^ADDRESS_4^POSTCODE1^POSTCODE2^FEATURE1^FEATURE2^FEATURE3^FEATURE4^FEATURE5^FEATURE6^FEATURE7^FEATURE8^FEATURE9^FEATURE10^SUMMARY^DESCRIPTION^BRANCH_ID^STATUS_ID^BEDROOMS^PRICE^PRICE_QUALIFIER^PROP_SUB_ID^CREATE_DATE^UPDATE_DATE^DISPLAY_ADDRESS^PUBLISHED_FLAG^LET_DATE_AVAILABLE^LET_TYPE_ID^LET_FURN_ID^LET_RENT_FREQUENCY^TENURE_TYPE_ID^TRANS_TYPE_ID^NEW_HOME_FLAG^EXACT_LATITUDE^EXACT_LONGITUDE^MEDIA_IMAGE_00^MEDIA_IMAGE_TEXT_00^MEDIA_IMAGE_01^MEDIA_IMAGE_TEXT_01^MEDIA_IMAGE_02^MEDIA_IMAGE_TEXT_02^MEDIA_IMAGE_03^MEDIA_IMAGE_TEXT_03^MEDIA_IMAGE_04^MEDIA_IMAGE_TEXT_04^MEDIA_IMAGE_05^MEDIA_IMAGE_TEXT_05^MEDIA_IMAGE_06^MEDIA_IMAGE_TEXT_06^MEDIA_IMAGE_07^MEDIA_IMAGE_TEXT_07^MEDIA_IMAGE_08^MEDIA_IMAGE_TEXT_08^MEDIA_IMAGE_09^MEDIA_IMAGE_TEXT_09^MEDIA_IMAGE_10^MEDIA_IMAGE_TEXT_10^MEDIA_IMAGE_11^MEDIA_IMAGE_TEXT_11^MEDIA_IMAGE_12^MEDIA_IMAGE_TEXT_12^MEDIA_IMAGE_13^MEDIA_IMAGE_TEXT_13^MEDIA_IMAGE_14^MEDIA_IMAGE_TEXT_14^MEDIA_IMAGE_15^MEDIA_IMAGE_TEXT_15^MEDIA_IMAGE_16^MEDIA_IMAGE_TEXT_16^MEDIA_IMAGE_17^MEDIA_IMAGE_TEXT_17^MEDIA_IMAGE_18^MEDIA_IMAGE_TEXT_18^MEDIA_IMAGE_19^MEDIA_IMAGE_TEXT_19^MEDIA_IMAGE_20^MEDIA_IMAGE_TEXT_20^MEDIA_IMAGE_21^MEDIA_IMAGE_TEXT_21^MEDIA_IMAGE_22^MEDIA_IMAGE_TEXT_22^MEDIA_IMAGE_23^MEDIA_IMAGE_TEXT_23^MEDIA_IMAGE_24^MEDIA_IMAGE_TEXT_24^MEDIA_IMAGE_60^MEDIA_IMAGE_TEXT_60^MEDIA_FLOOR_PLAN_00^MEDIA_FLOOR_PLAN_TEXT_00^MEDIA_FLOOR_PLAN_01^MEDIA_FLOOR_PLAN_TEXT_01^MEDIA_FLOOR_PLAN_02^MEDIA_FLOOR_PLAN_TEXT_02^MEDIA_FLOOR_PLAN_03^MEDIA_FLOOR_PLAN_TEXT_03^MEDIA_DOCUMENT_00^MEDIA_DOCUMENT_TEXT_00^MEDIA_DOCUMENT_01^MEDIA_DOCUMENT_TEXT_01^MEDIA_DOCUMENT_50^MEDIA_DOCUMENT_TEXT_50^MEDIA_DOCUMENT_51^MEDIA_DOCUMENT_TEXT_51^MEDIA_VIRTUAL_TOUR_00^MEDIA_VIRTUAL_TOUR_TEXT_00^MEDIA_VIRTUAL_TOUR_01^MEDIA_VIRTUAL_TOUR_TEXT_01^~

    #DATA#
    12345_ID^123 Road^Town^County^^NR19^0FX^Three Good Sized Bedrooms^Character Features^Rear Garden^Two Separate Bathrooms^Central Location^Great Condition Throughout^^^^^A spacious three bedroom home offered to the market having been renovated to a high standard (contd...)^A spacious three bedroom Victorian home offered to the market having been renovated to a high standard over the years, while maintaining the original character features.^123^0^2^123^0^2^2222-10-02 00:00:00^2017-01-01 16:34:57^Road, Town, County, NR19^1^^0^^0^1^1^^ 51.0000^-0.50002^http://example.com/pic.jpg^Caption^http://example.com/pic.jpg^Caption^http://example.com/pic.jpg^Master Bedroom^http://example.com/pic.jpg^Garden^http://example.com/pic.jpg^Dining Room^http://example.com/pic.jpg^Bathroom^http://example.com/pic.jpg^Bedroom 2^http://example.com/pic.jpg^Landing^http://example.com/pic.jpg^External^http://example.com/pic.jpg^Bedroom 3^http://example.com/pic.jpg^Dining Room^http://example.com/pic.jpg^Kitchen^http://example.com/pic.jpg^Master Bedroom^http://example.com/pic.jpg^Garden^^^^^^^^^^^^^^^^^^^^^^^http://example.com/epc.png^EPC^http://exampel.com/floorplan.jpg^Floorplan^^^^^^^http://example.com/link/to/prop^WebDetails^http://example.com/pdf.pdf^Particulars^^^^^^^^^~

**Comment by ralphsaunders** [comment] 2017-05-31 11:41
It would appear that the code could be extended in the same fashion as the tab delimitation support. https://github.com/antonycourtney/tad/blob/master/src/csvimport.js#L218

**Comment by trowt** [comment] 2017-05-31 14:22
I would also like to see this. I almost always use pipe-delimited files.

**Comment by badbart** [comment] 2017-06-01 04:53
And semicolon separated. We almost entirely use semicolon separated files

**Comment by antonycourtney** [comment] 2017-06-03 18:20
Duplicate of #52, closing.

**Closed by antonycourtney** 2017-06-03 18:20 UTC
